### ISSUE TITLE
Answer Link to Frontend Job Interview Questions Invalid

### ISSUE THREAD

**Issue by Yuting1007** [Jobeir/front-end-interview-preparation-guide#3]
As title (error 404). I would really appreciate it if fixing this! This page is really helpful when preparing for the frontend interview.

**Comment by brotzky** [comment]
It seems the answers were taken down. Here's a thread from the repo discussing it: https://github.com/h5bp/Front-end-Developer-Interview-Questions/pull/215#issuecomment-68835978

Sorry :\
